trigger:
- master

steps:
- task: AzureFileCopy@3
  displayName: 'Copy template update to new version on Azure blob storage $(storageSandbox)/$(ContainerName)'
  inputs:
    SourcePath: template
    azureSubscription: '$(azureSubscriptionSandbox)'
    Destination: AzureBlob
    storage: $(storageSandbox)
    ContainerName: $(ContainerName)
    BlobPrefix: arm/$(Build.Repository.Name)/$(Build.BuildNumber)

- task: AzureFileCopy@3
  displayName: 'Update latest folder in $(storageSandbox)/$(ContainerName)'
  inputs:
    SourcePath: template
    azureSubscription: '$(azureSubscriptionSandbox)'
    Destination: AzureBlob
    storage: $(storageSandbox)
    ContainerName: $(ContainerName)
    BlobPrefix: arm/$(Build.Repository.Name)/latest